In [ ]:
# Cargamos la librería
import numpy as np

# Definimos los dos arrays o vectores
valtura = np.array([ 1.67, 1.73, 1.76, 1.85, 1.77, 1.73 ])
vmasa = np.array([ 65.0, 79.2, 76.7, 82.0, 72.5, 66.1 ])

# Y calculamos normalmente como con cualquier otro tipo numérico
vmasa / (valtura ** 2)


array([23.30668005, 26.46262822, 24.76110537, 23.95909423, 23.14149829,
       22.08560259])

Mucho más conciso y fácil de entender, ¿no crees? Simplemente hemos creado dos vectores con Numpy para almacenar las alturas y pesos, y después realizamos las operaciones directamente sobre ellos.

### _Arrays_

El tipo básico para trabajar en NumPy es el _array_. Estos objetos representan vectores o matrices multidimensionales, en las que todos los elementos son del mismo tipo, en general numérico.

En el ejemplo anterior ya hemos visto cómo crear un nuevo array utilizando una lista de valores. De esta forma, definimos un array de dimensión 1, es decir, un vector. Sigamos con otro ejemplo sencillo.


In [ ]:
# Un vector (dimensión 1) con tres elementos
v_1d = np.array([1, 2, 3])

In [ ]:
# Número de dimensiones del array
print(v_1d.ndim)        # 1

1


In [ ]:
# Número de elementos en cada dimensión del array
print(v_1d.shape)       # (3,)

(3,)


In [ ]:
# Número total de elementos del array
print(v_1d.size)        # 3

3


In [ ]:
# Tipo de los elementos
print(v_1d.dtype)       # int64 (enteros)

int32


In [ ]:
# Ahora vamos a crear una matriz
# utilizando listas anidadas
m_2d = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Veamos el contenido
print(m_2d)             # [[1 2 3]
                        #  [4 5 6]]

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Es un array de 2 dimensiones (una matriz)
print(m_2d.ndim)        # 2

2


In [ ]:
# El primer eje o dimensión tiene tamaño 2 (filas)
# El segundo eje o dimensión tiene tamaño 3 (columnas)
print(m_2d.shape)       # (2, 3)

(2, 3)


In [ ]:
# Número total de elementos del array
print(m_2d.size)        # 6

6


In [ ]:
# Tipo de los elementos
print(m_2d.dtype)       # float64 (coma flotante)

float64


In [ ]:
# También podemos indicar el tipo de los elementos
# al crear el array, con el argumento 'dtype'
np.array([[1, 2, 3], [4, 5, 6]], dtype='float64')

array([[1., 2., 3.],
       [4., 5., 6.]])

En este código hemos creado un vector unidimensional (`v_1d`) y una matriz bidimensional (`m_2d`). En el segundo caso, lo hacemos pasando una lista de listas. En general, cuando usamos esta forma de construir un array, pasando una secuencia de elementos, el nivel de anidación determinará el número de dimensiones que tenga el array.

Además, vemos cómo hacer para consultar algunas propiedades de un array, como el número de dimensiones, la forma o tamaño de las dimensiones, el número de elementos o su tipo. También habrás visto en el último ejemplo cómo indicar el tipo de los elementos al crear el array.

Sigamos con más formas de crear arrays especificando sucesiones de elementos con `np.arange()` y `np.linspace()`

In [ ]:
# La función np.arange() es similar al "range()" normal
# pero crea arrays en lugar de listas
m1 = np.arange(15)
print(m1)                   # [ 0  1  2 ..., 12 13 14]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# Al igual que range(), se puede indicar 
# el limite inicial, final y el tamaño del paso
m2 = np.arange(1, 10, 2)
print(m2)                   # [1 3 5 7 9]

[1 3 5 7 9]


In [ ]:
# Si queremos crear un array dividiendo un intervalo
# en N elementos equiespaciados, podemos usar np.linspace()
m3 = np.linspace(0, 10, 5)  # Genera 5 núms entre 0 y 10 (ambos incluidos)
print(m3)                   # [  0.    2.5   5.    7.5  10. ]

[ 0.   2.5  5.   7.5 10. ]


Si recuerdas la función `range()` que hemos utilizado múltiples veces para generar secuencias, notarás que la función `np.arange()` es prácticamente idéntica, solo que crea objetos de tipo `ndarray` (que es el tipo de los arrays en NumPy).

La función `np.linspace()` es un poco distinta, porque en lugar de darle el tamaño del _paso_, lo que hace es generar un número dado de valores igualmente espaciados entre los dos límites que le indicas (incluyendo ambos en el resultado).

Al operar con vectores y matrices, será habitual que tengamos que utilizar construcciones especiales, como matrices unidad, o arrays con todos los elementos cero o iguales... NumPy incluye varias funciones muy prácticas para crear estos tipos de arrays más comunes.


In [ ]:
# Crear un vector con 5 ceros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Crear una matriz 2x3 de ceros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Crear una matriz 2x3 de unos
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Crear una matrix 2x3 rellenada con el mismo valor (99) 
# para todos los elementos
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
# Crear una matriz identidad 3x3
# (1 en la diagonal, 0 en el resto)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

También podemos crear arrays con valores generados aleatoriamente a partir de distintas distribuciones de probabilidad.

In [ ]:
# Fijamos la semilla aleatoria (por reproducibilidad)
np.random.seed(42)

In [ ]:
# Crear una matrix 2x3
# rellenada con numeros aleatorios en [0, 1)
np.random.random((2,3))

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [ ]:
# Distribución uniforme en [a, b)
np.random.uniform(0, 10, size=(2,3))

array([[0.58083612, 8.66176146, 6.01115012],
       [7.08072578, 0.20584494, 9.69909852]])

In [ ]:
# Distribución normal (media=0, desv.tipica=1)
np.random.normal(0, 1, size=(2,3))

array([[-0.46947439,  0.54256004, -0.46341769],
       [-0.46572975,  0.24196227, -1.91328024]])

In [ ]:
# Muestrear un array
vbase = np.arange(10)
# con reemplazo (permitiendo valores replicados)
np.random.choice(vbase, size=8, replace=True)

array([8, 0, 9, 2, 6, 3, 8, 2])

In [ ]:
# sin reemplazo (cada valor solo puede aparecer una vez)
np.random.choice(vbase, size=8, replace=False)

array([8, 7, 5, 3, 1, 0, 9, 6])