In [ ]:
import numpy as np

### Copias y vistas de _arrays_

Cuando trabajamos con arrays, algunas operaciones crean una nueva copia de los datos a partir de las variables originales. Pero en otros casos, por eficiencia, la librería NumPy usa y devuelve una referencia o una vista sobre la variable original.

Conocer en qué casos hace una cosa u otra es muy importante, porque si manipulamos un array resultado podemos estar cambiando también el array original inadvertidamente. Los tres casos a tener en mente son los siguientes.

#### Referencia (o trabajo sin copia de datos)

Cuando asignamos una variable de tipo array a otra variable, simplemente se está definiendo una nueva referencia al mismo array en memoria. No se crea una nueva copia de los datos.

Esto significa que cualquier cambio que hagamos en una variable afectará al resto que referencian al mismo array.

In [ ]:
# Creamos un nuevo array
v1 = np.arange(10)
print(v1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Asignamos el array a otra variable
v2 = v1

In [ ]:
# Modificamos un valor en el segundo array
v2[3] = 999

In [ ]:
# Vemos que el cambio afecta tambien a v1
print(v1)

[  0   1   2 999   4   5   6   7   8   9]


In [ ]:
# v1 y v2 son referencias que apuntan al mismo contenido
v2 is v1

True

Si haces memoria, este caso no es distinto de lo que ocurre con otras variables y estructuras de datos, como ya vimos con las listas.

#### Vista (o copia superficial)

Cuando definimos un nuevo array manipulando las dimensiones de otro (p.ej. con `reshape`) o cuando seleccionamos una _rebanada_ de elementos, estamos creando una copia superficial o _vista_ alternativa del array. La trasposición de un array también genera una _vista_.

Con una copia superficial, podemos modificar la _forma_ o dimensiones de la _vista_ sin afectar al array original. No cambiaremos su forma.

Pero si modificamos cualquiera de los valores en la copia superficial, sí que estaremos cambiando los valores en el array original.

In [ ]:
# Creamos un nuevo array
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Asignamos una versión manipulada del array (con reshape())
# a otra variable
m1 = v1.reshape(3,4)
print(m1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Podemos ver el array de partida para la vista con la propiedad 'base'
# Comprobamos que el array base de m1 y v1 apuntan al mismo contenido
m1.base is v1

True

In [ ]:
# Si modificamos la forma del segundo array...
m1.shape = (4,3)
print(m1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# ... no cambiamos la forma del original
v1.shape
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Pero si modificamos el valor de un elemento...
m1[0, 2] = 999
print(m1)

[[  0   1 999]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [ ]:
# ... modificamos los datos en el original
print(v1)

[  0   1 999   3   4   5   6   7   8   9  10  11]


#### Copia profunda

Si queremos una copia total e independiente de un array, podemos utilizar el método `copy()`. De esta forma generamos una copia exacta de forma y contenido, pero sin compartir estructura ni valores en memoria con el array original.

Cuando seleccionamos elementos de un array indicando directamente una lista de índices, o usando una máscara booleana, obtenemos un array completamente nuevo (en lugar de una _vista_ como al seleccionar _rebanadas_).

In [ ]:
v1 = np.arange(10)
print(v1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Creamos una copia nueva
v2 = v1.copy()

# Los arrays tienen elementos con valores iguales
print(v2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Pero el array base de v2 no es v1
# v2 referencia a una estructura distinta independiente
v2.base is v1

False

In [ ]:
v2[0] = 999
print(v2)
print(v1)

[999   1   2   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
