In [ ]:
import numpy as np

#### Operaciones de agregación y estadísticas

NumPy nos permite calcular valores agregados o estadísticos sobre un array, como la suma de sus elementos o la media. Podemos realizar estas operaciones tomando todos los elementos del array, o agregar en un determinado eje o dimensión (por ejemplo, por filas o columnas en una matriz).

In [ ]:
# Creamos una matriz
m3 = np.arange(1,10).reshape(3,3)
print(m3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Suma de todos los elementos del array
np.sum(m3)

45

In [ ]:
# Suma de los elementos de cada columna
np.sum(m3, axis = 0)

array([12, 15, 18])

In [ ]:
# Suma de los elementos de cada fila
np.sum(m3, axis = 1)

array([ 6, 15, 24])

In [ ]:
# Media
np.mean(m3)

5.0

In [ ]:
np.mean(m3, axis = 0)

array([4., 5., 6.])

In [ ]:
# Desviación estándar
np.std(m3)

2.581988897471611

In [ ]:
# Máximos y mínimos
np.min(m3, axis = 0)

array([1, 2, 3])

In [ ]:
np.max(m3, axis = 1)

array([3, 6, 9])

In [ ]:
np.median(m3)

5.0

In [ ]:
# Suma acumulada de elementos
np.cumsum(m3)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [ ]:
np.cumsum(m3, axis = 0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)