### Leyendo de fichero

En muchas ocasiones los datos con los que tenemos que trabajar estarán almacenados en un fichero. Es habitual utilizar ficheros de tipo _CSV_ como formato de intercambio de datos, ya que es un formato en texto plano sencillo de manipular y que está soportado por la mayoria de software de manejo de datos, tanto para importar como para exportar información.

NumPy también permite leer datos de ficheros _CSV_ con la función `np.genfromtext()`. Solo tenemos que indicar el nombre del fichero y especificar otras opciones habituales, como cuál es el caracter delimitador, si tiene fila de encabezados, qué valores indican un elemento ausente, etc.

In [ ]:
# Leemos una matriz de un fichero CSV de ejemplo
# Modifica la ruta de directorios hasta el fichero
# dependiendo de dónde hayas descargado el material de la unidad
matriz = np.genfromtxt(fname = "../U09_datasets/ejemplo_numpy_datos.csv", delimiter = ";", skip_header = 0)
print(matriz)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
