In [ ]:
import numpy as np

#### Álgebra de vectores y matrices

Naturalmente, la librería NumPy incorpora las principales operaciones de transformación y álgebra lineal con vectores y matrices. Alguna de ellas ya la hemos visto, como el cálculo de la matriz traspuesta.


In [ ]:
m1 = np.array([1, 3, 4, 7, 5, 8, 2, 9, 6]).reshape(3,3)
print(m1)

[[1 3 4]
 [7 5 8]
 [2 9 6]]


In [ ]:
# Trasponer la matriz
m1.transpose()

array([[1, 7, 2],
       [3, 5, 9],
       [4, 8, 6]])

In [ ]:
# ... o más breve
m1.T

array([[1, 7, 2],
       [3, 5, 9],
       [4, 8, 6]])

Entre otras operaciones, podemos calcular la inversa de una matriz o su traza.

In [ ]:
# Matriz inversa
m1_inv = np.linalg.inv(m1)
print(m1_inv)

[[-0.45652174  0.19565217  0.04347826]
 [-0.2826087  -0.02173913  0.2173913 ]
 [ 0.57608696 -0.0326087  -0.17391304]]


In [ ]:
# Traza de la matriz
# (suma de elementos de la diagonal principal)
m1.trace()

12

También disponemos del producto interno de vectores y matrices. Cuando tengas que realizar estas operaciones, recuerda no confundirte con la multiplicación elemento a elemento de arrays (operador `'*'`).

In [ ]:
# Para dos vectores...
v1 = np.array([1, 4, 6])
v2 = np.array([3, 5, 2])

In [ ]:
# El producto interior de dos vectores
# genera un escalar
v1.dot(v2)      # 35   = (1 * 3) + (4 * 5) + (6 * 2)

35

In [ ]:
# Para dos matrices...
m1 = np.array([4, 1, 1, 2]).reshape(2,2)
m2 = np.array([1, 3, 5, 1]).reshape(2,2)

In [ ]:
# El producto interior de dos matrices
# genera una matriz
mp1 = m1.dot(m2)
print(mp1)

[[ 9 13]
 [11  5]]


In [ ]:
# El producto interior de dos matrices NO es conmutativo !!
mp2 = m2.dot(m1)
print(mp2)

[[ 7  7]
 [21  7]]


In [ ]:
# El producto interior de una matriz y un vector
# es un vector
v3 = np.array([3, 5])
mv = m1.dot(v3)
print(mv)

[17 13]
